name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up PureScript toolchain
        uses: purescript-contrib/setup-purescript@main
        with:
          purs-tidy: "latest"

      - name: Cache PureScript dependencies
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-spago-${{ hashFiles('updater/**/*.dhall') }}
          path: |
            updater/.spago
            updater/output

      - name: Install dependencies
        run: spago install
        working-directory: updater

      - name: Build source
        run: spago build --no-install
        working-directory: updater

      - name: Lint source
        run: purs-tidy check src test
        working-directory: updater
